global proc findWhere()
{
	string $whereFile=`whatIs findWhere`;
	string $buffer[];
	$numTokens = `tokenize $place ":" $buffer`;
	$place=strip ($buffer[1]+":"+$buffer[2]);
	string $buffer1[];
	$numTokens = `tokenize $place "/" $buffer1`;
	$place=$buffer1[0];
	for ($i=1;$i<($numTokens-1);$i++)
	{
		$place=$place+"/"+$buffer1[$i];}
		return	$place;
	}
	string $needToCopy=`tellMeWhereCST`;
	python ("import sys");
	string $logo_path_install= ($needToCopy+"/data/icon_data/UI_main/");

}
